# Generated by Django 5.0.4 on 2026-08-26 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0028_grupos_zonas_sin_clinica'),
        ('pacientes', '0008_alter_configuracionfacial_min_det_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionFallida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(choices=[('recordatorio_cita', 'Recordatorio de cita'), ('checkin_otp', 'Codigo de check-in'), ('envio_cotizacion', 'Envio de cotizacion'), ('envio_formula', 'Envio de orden medica')], max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_fallidas', to='clinicas.clinica')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_fallidas', to='pacientes.paciente')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_fallidas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones_fallidas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinica', 'resuelta'], name='notificacio_clinica_880ae1_idx')],
            },
        ),
    ]
