# Generated by Django 5.0.4 on 2026-09-15 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0040_quitar_otp_fields'),
        ('notificaciones', '0001_initial'),
        ('pacientes', '0009_configuracionfacial_min_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionfallida',
            name='tipo_notificacion',
            field=models.CharField(choices=[('recordatorio_cita', 'Recordatorio de cita'), ('checkin_otp', 'Codigo de check-in'), ('envio_cotizacion', 'Envio de cotizacion'), ('envio_formula', 'Envio de orden medica'), ('firma_documento', 'Firma de documento')], max_length=30),
        ),
        migrations.CreateModel(
            name='EnvioWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recordatorio_cita', 'Recordatorio de cita'), ('checkin_otp', 'Codigo de check-in'), ('envio_cotizacion', 'Envio de cotizacion'), ('envio_formula', 'Envio de orden medica'), ('firma_documento', 'Firma de documento')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_whatsapp', to='clinicas.clinica')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_whatsapp', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'envios_whatsapp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinica', 'created_at'], name='envios_what_clinica_ffa96e_idx')],
            },
        ),
    ]
