# Generated by Django 5.0.4 on 2026-09-25 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0045_whatsapp_numero_propio_addon'),
        ('notificaciones', '0002_whatsapp_addon_paquete'),
        ('pacientes', '0009_configuracionfacial_min_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviowhatsapp',
            name='datos',
            field=models.JSONField(blank=True, default=dict, help_text='Lo necesario para reenviar por el número compartido si el envío propio falla.'),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='error_externo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('incierto', 'Sin confirmar'), ('fallido', 'Fallido')], default='enviado', max_length=10),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='lyvio_conversation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='lyvio_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='motivo_ruta',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='respaldo_de',
            field=models.OneToOneField(blank=True, help_text='Envío propio fallido que este envío por el compartido reemplazó.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo', to='notificaciones.enviowhatsapp'),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='ruta',
            field=models.CharField(choices=[('compartido', 'Número compartido'), ('propio', 'Número propio')], default='compartido', max_length=10),
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ConexionWhatsappPropio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pago_meta_configurado', models.BooleanField(default=False, help_text='La clínica confirmó que agregó un método de pago en Meta.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conexion_whatsapp_propio', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'conexiones_whatsapp_propio',
            },
        ),
        migrations.CreateModel(
            name='NumeroWhatsapp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lyvio_inbox_id', models.CharField(max_length=64, unique=True)),
                ('waba_id', models.CharField(max_length=64)),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('business_id', models.CharField(blank=True, max_length=64)),
                ('numero_visible', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('conectado', 'Conectado'), ('plantillas_pendientes', 'Plantillas pendientes de aprobación'), ('activo', 'Activo'), ('error', 'Error')], default='conectado', max_length=25)),
                ('ultimo_error', models.TextField(blank=True)),
                ('ultimo_chequeo_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='notificaciones.conexionwhatsapppropio')),
            ],
            options={
                'db_table': 'numeros_whatsapp',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactoLyvio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono (E.164) con el que se creó; si el paciente lo cambia, se vuelve a resolver.', max_length=20)),
                ('contact_id', models.CharField(max_length=64)),
                ('conversation_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_lyvio', to='pacientes.paciente')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='notificaciones.numerowhatsapp')),
            ],
            options={
                'db_table': 'contactos_lyvio',
            },
        ),
        migrations.AddField(
            model_name='conexionwhatsapppropio',
            name='numero_por_defecto',
            field=models.OneToOneField(blank=True, help_text='Número para envíos sin sede, sedes sin asignación (incluidas las nuevas) y respaldo cuando el número de una sede no está activo. El primero que se conecta queda como número por defecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notificaciones.numerowhatsapp'),
        ),
        migrations.CreateModel(
            name='AsignacionWhatsappSede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('por_defecto', 'Número por defecto'), ('numero', 'Un número de la clínica'), ('cliniq', 'Número de CliniQ')], default='por_defecto', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_whatsapp', to='clinicas.sede')),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='notificaciones.conexionwhatsapppropio')),
                ('numero', models.ForeignKey(blank=True, help_text='Solo con tipo `numero`. Si el número se borra, la sede vuelve al por defecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='notificaciones.numerowhatsapp')),
            ],
            options={
                'db_table': 'asignaciones_whatsapp_sede',
            },
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='notificaciones.numerowhatsapp'),
        ),
        migrations.CreateModel(
            name='PlantillaWhatsappNumero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recordatorio_cita', 'Recordatorio de cita'), ('checkin_otp', 'Codigo de check-in'), ('envio_cotizacion', 'Envio de cotizacion'), ('envio_formula', 'Envio de orden medica'), ('firma_documento', 'Firma de documento')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('PAUSED', 'Pausada'), ('DISABLED', 'Deshabilitada'), ('ERROR', 'No se pudo crear')], default='PENDING', max_length=10)),
                ('categoria', models.CharField(blank=True, help_text='La categoría que dejó Meta.', max_length=20)),
                ('ultimo_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='notificaciones.numerowhatsapp')),
            ],
            options={
                'db_table': 'plantillas_whatsapp_numero',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactolyvio',
            constraint=models.UniqueConstraint(fields=('numero', 'paciente'), name='contacto_lyvio_unico'),
        ),
        migrations.AddConstraint(
            model_name='plantillawhatsappnumero',
            constraint=models.UniqueConstraint(fields=('numero', 'nombre', 'idioma'), name='plantilla_unica_por_numero'),
        ),
    ]
