# Generated by Django 5.0.4 on 2026-09-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_whatsapp_numero_propio'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerowhatsapp',
            name='bloqueo',
            field=models.CharField(blank=True, choices=[('', 'Sin bloqueo'), ('pago', 'Falta el método de pago en Meta'), ('conexion', 'Meta desconectó o restringió el número')], default='', max_length=10),
        ),
    ]
