# Generated by Django 5.0.4 on 2026-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_numero_whatsapp_bloqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerowhatsapp',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Solo para el bloqueo por límite: se levanta solo a esta hora.', null=True),
        ),
        migrations.AddField(
            model_name='numerowhatsapp',
            name='limite_mensajes',
            field=models.CharField(blank=True, help_text='Límite diario de Meta del portfolio (TIER_250, TIER_2K... TIER_UNLIMITED); vacío si no se ha leído.', max_length=30),
        ),
        migrations.AlterField(
            model_name='numerowhatsapp',
            name='bloqueo',
            field=models.CharField(blank=True, choices=[('', 'Sin bloqueo'), ('pago', 'Falta el método de pago en Meta'), ('conexion', 'Meta desconectó o restringió el número'), ('limite', 'Meta frenó los envíos por límite diario')], default='', max_length=10),
        ),
    ]
