# Generated by Django 5.0.4 on 2026-05-26 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0007_servicio_vigencia_meses'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHistoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tabs_activos', models.JSONField(blank=True, default=list)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_historia', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'configuracion_historia',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSignosVitales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campos_extra', models.JSONField(blank=True, default=list)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_signos', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'configuracion_signos_vitales',
            },
        ),
    ]
