# Generated by Django 5.0.4 on 2026-06-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_configuracionregistropublico'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionwizard',
            name='paso_verificacion_facial',
            field=models.BooleanField(default=False),
        ),
    ]
