# Generated by Django 5.0.4 on 2026-08-24 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0028_grupos_zonas_sin_clinica'),
        ('configuracion', '0007_documenso_template_pdf_campos'),
        ('consentimientos', '0002_h36_plantilla_asistencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documensoconsentimientotemplate',
            options={'ordering': ['nombre', 'tipo']},
        ),
        migrations.CreateModel(
            name='ConfiguracionCartera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requiere_consentimiento_promocional', models.BooleanField(default=False)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_cartera', to='clinicas.clinica')),
                ('plantilla_compromiso_pago', models.ForeignKey(blank=True, help_text='Plantilla (ambito=cotizacion) usada al aceptar una cotizacion, si esta activo el requisito.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='consentimientos.plantillaconsentimiento')),
            ],
            options={
                'db_table': 'configuracion_cartera',
            },
        ),
    ]
