# Generated by Django 5.0.4 on 2026-09-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_configuracionwizard_foto_control_obligatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='documensoconsentimientotemplate',
            name='requiere_firma_profesional',
            field=models.BooleanField(default=True, help_text='Si True, el documento lo firma también el profesional que atiende la primera cita. Si False, se sella solo con la firma del paciente.'),
        ),
        migrations.AlterField(
            model_name='documensoconsentimientotemplate',
            name='campos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de campos de firma/texto/fecha/checkbox con posición en el PDF. Cada campo indica su firmante (paciente|profesional); los del profesional llevan un rol fijo (firma|nombre|tp) que se llena automáticamente al firmar.'),
        ),
    ]
