# Generated by Django 5.0.4 on 2026-10-07 19:42

from django.db import migrations, models


def agregar_pestanas_nuevas(apps, schema_editor):
    """Seguimiento y Zonas no estaban en la lista del backend, pero la historia
    siempre las mostraba. Una configuracion ya guardada las agrega para que no
    se oculten al empezar a leerla."""
    ConfiguracionHistoria = apps.get_model("configuracion", "ConfiguracionHistoria")
    for config in ConfiguracionHistoria.objects.exclude(tabs_activos=[]):
        tabs = list(config.tabs_activos or [])
        nuevas = [slug for slug in ("mediciones", "zonas") if slug not in tabs]
        if nuevas:
            config.tabs_activos = tabs + nuevas
            config.save(update_fields=["tabs_activos"])


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_documensoconsentimientotemplate_requiere_firma_profesional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhistoria',
            name='atencion_tabs_activos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(agregar_pestanas_nuevas, migrations.RunPython.noop),
    ]
