# Generated by Django 5.0.4 on 2026-04-17 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinicas", "0002_servicio_sede"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaGasto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorias_gasto",
                        to="clinicas.clinica",
                    ),
                ),
            ],
            options={
                "db_table": "categorias_gasto",
                "ordering": ["nombre"],
                "unique_together": {("clinica", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="GastoCaja",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("soporte_foto", models.ImageField(blank=True, null=True, upload_to="gastos/%Y/%m/")),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("aprobado_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="caja.categoriagasto",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_caja",
                        to="clinicas.sede",
                    ),
                ),
            ],
            options={
                "db_table": "gastos_caja",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("total_cobros", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_gastos", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("efectivo_contado", models.DecimalField(decimal_places=2, max_digits=12)),
                ("diferencia", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cierres_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cierres_caja",
                        to="clinicas.sede",
                    ),
                ),
            ],
            options={
                "db_table": "cierres_caja",
                "ordering": ["-fecha"],
                "unique_together": {("sede", "fecha")},
            },
        ),
    ]
