# Generated by Django 5.0.4 on 2026-09-01 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('clinicas', '0029_servicio_descuento_maximo_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastocaja',
            name='aprobado_en',
        ),
        migrations.RemoveField(
            model_name='gastocaja',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='gastocaja',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='gastocaja',
            name='motivo_rechazo',
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Fondo con el que se abre la caja la primera vez. Después arrastra.', max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_responsable', to=settings.AUTH_USER_MODEL)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caja', to='clinicas.sede')),
            ],
            options={
                'db_table': 'cajas',
                'ordering': ['sede__nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('abierta_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abierta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_abiertas', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='caja.caja')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesiones_caja',
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.AddField(
            model_name='gastocaja',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión de caja bajo la que se registró. Null = gasto histórico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='caja.sesioncaja'),
        ),
        migrations.DeleteModel(
            name='CierreCaja',
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('caja',), name='una_sesion_abierta_por_caja'),
        ),
    ]
