# Generated by Django 5.0.4 on 2026-09-01 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_caja_por_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastocaja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
