services:
  frontend:
    image: jorgeavilag/cliniq:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3000"
    networks:
      - cliniq_network

networks:
  cliniq_network:
    external: true
    name: cliniq_network
