services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: cliniq-frontend:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - cliniq_network

networks:
  cliniq_network:
    external: true
    name: cliniq_network
