# Generated by Django 5.0.4 on 2026-09-02 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0030_clinica_modo_puesta_en_marcha'),
        ('pacientes', '0008_alter_configuracionfacial_min_det_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMigracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('paciente_en_curso', 'Paciente en curso'), ('saldo_cartera', 'Saldo de cartera'), ('otro', 'Otro')], default='paciente_en_curso', max_length=30)),
                ('nota', models.CharField(blank=True, max_length=300)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('revertido_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_migracion', to='clinicas.clinica')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_migracion_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_migracion', to='pacientes.paciente')),
                ('revertido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_migracion_revertidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lotes_migracion',
                'ordering': ['-created_at'],
            },
        ),
    ]
