# Generated by Django 5.0.4 on 2026-04-13 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('clinicas', '0002_servicio_sede'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaConsentimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('contenido_html', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_consentimiento', to='clinicas.clinica')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_consentimiento', to='clinicas.servicio')),
            ],
            options={
                'db_table': 'plantillas_consentimiento',
                'ordering': ['nombre', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_snapshot', models.TextField()),
                ('hash_contenido', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('revocado', 'Revocado')], default='pendiente', max_length=20)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('firma_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('firma_user_agent', models.TextField(blank=True)),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='consentimientos/%Y/%m/')),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.TextField(blank=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='agenda.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='pacientes.paciente')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='consentimientos.plantillaconsentimiento')),
            ],
            options={
                'db_table': 'consentimientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
