# Generated by Django 5.0.4 on 2026-06-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0018_h33_clinica_config_deuda'),
        ('consentimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documenso_template_token', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_asistencia', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'plantillas_asistencia',
                'ordering': ['nombre'],
            },
        ),
    ]
