# Generated by Django 5.0.4 on 2026-08-24 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_cita_firma_asistencia_signing_token'),
        ('consentimientos', '0002_h36_plantilla_asistencia'),
        ('cotizaciones', '0011_h40_item_campana'),
        ('pacientes', '0008_alter_configuracionfacial_min_det_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimiento',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='cotizaciones.cotizacion'),
        ),
        migrations.AddField(
            model_name='plantillaconsentimiento',
            name='ambito',
            field=models.CharField(choices=[('cita', 'Cita'), ('cotizacion', 'Cotización (compromiso de pago / compra)')], default='cita', max_length=20),
        ),
        migrations.AlterField(
            model_name='consentimiento',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='agenda.cita'),
        ),
        migrations.AddConstraint(
            model_name='consentimiento',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cita__isnull', False), ('cotizacion__isnull', True)), models.Q(('cita__isnull', True), ('cotizacion__isnull', False)), _connector='OR'), name='consentimiento_cita_xor_cotizacion'),
        ),
    ]
