# Generated by Django 5.0.4 on 2026-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentimientos', '0003_consentimiento_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimiento',
            name='documenso_documento_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='documenso_signing_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
