services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: cliniq-backend:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - cliniq_network
      - shared-services
    volumes:
      - staticfiles:/app/staticfiles

networks:
  cliniq_network:
    name: cliniq_network
    driver: bridge
  shared-services:
    external: true
    name: shared-services

volumes:
  staticfiles:
