# Generated by Django 5.0.4 on 2026-04-13 16:33

import apps.agenda.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_servicio_sede'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('profesional', models.ForeignKey(limit_choices_to={'rol': 'profesional'}, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueos_agenda', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueos_agenda', to='clinicas.sede')),
            ],
            options={
                'db_table': 'bloqueos_agenda',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistio')], default='pendiente', max_length=20)),
                ('estado_confirmacion', models.CharField(choices=[('sin_enviar', 'Sin enviar'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('sin_respuesta', 'Sin respuesta')], default='sin_enviar', max_length=20)),
                ('canal_confirmacion', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('llamada', 'Llamada')], max_length=20)),
                ('canal_origen', models.CharField(choices=[('presencial', 'Presencial'), ('telefono', 'Telefono'), ('web', 'Web'), ('redes', 'Redes')], default='presencial', max_length=20)),
                ('notas_internas', models.TextField(blank=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_confirmadas_manual', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(limit_choices_to={'rol': 'profesional'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clinicas.sede')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clinicas.servicio')),
            ],
            options={
                'db_table': 'citas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('expira_en', models.DateTimeField(default=apps.agenda.models.default_expira_en)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='agenda.cita')),
            ],
            options={
                'db_table': 'confirmacion_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['profesional', 'fecha_inicio'], name='citas_profesi_360636_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['sede', 'fecha_inicio'], name='citas_sede_id_cffe3a_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha_inicio'], name='citas_pacient_774b2f_idx'),
        ),
    ]
