# Generated by Django 5.0.4 on 2026-05-08 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_bloqueoagenda_profesional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConfirmacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado_resultante', models.CharField(max_length=20)),
                ('usuario_nombre', models.CharField(blank=True, max_length=200)),
                ('medio', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('llamada', 'Llamada telefonica'), ('sms', 'SMS'), ('presencial', 'Presencial'), ('link', 'Link de confirmacion'), ('email', 'Email')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_confirmacion', to='agenda.cita')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_confirmacion_citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registros_confirmacion',
                'ordering': ['-created_at'],
            },
        ),
    ]
