# Generated by Django 5.0.4 on 2026-05-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cita_estado_en_espera'),
        ('cotizaciones', '0002_itemcotizacion_periodicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='item_cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='cotizaciones.itemcotizacion'),
        ),
    ]
