# Generated by Django 5.0.4 on 2026-06-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_cita_item_cotizacion'),
        ('clinicas', '0012_add_duracion_min_tipo_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinicas.servicio'),
        ),
    ]
