# Generated by Django 5.0.4 on 2026-06-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_h6_3_servicio_opcional_duracion_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_manual_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
