# Generated by Django 5.0.4 on 2026-06-09 14:59

import apps.agenda.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_add_recordatorio_manual_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='checkin_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='checkin_foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.agenda.models.cita_checkin_upload_path),
        ),
        migrations.AddField(
            model_name='cita',
            name='checkin_foto_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='cita',
            name='checkin_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='checkin_metodo',
            field=models.CharField(blank=True, choices=[('otp_whatsapp', 'OTP WhatsApp'), ('foto_presencial', 'Foto presencial')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CitaCheckinOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('expira_en', models.DateTimeField(default=apps.agenda.models.cita_checkin_otp_expira_en)),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='agenda.cita')),
            ],
            options={
                'db_table': 'cita_checkin_otps',
            },
        ),
    ]
