# Generated by Django 5.0.4 on 2026-06-12 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_cita_checkin_fields'),
        ('clinicas', '0018_h33_clinica_config_deuda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueoagenda',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloqueoagenda',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloqueoagenda',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to='clinicas.clinica'),
        ),
        migrations.AddField(
            model_name='bloqueoagenda',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloqueoagenda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloqueoagenda',
            name='motivo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bloqueoagenda',
            name='profesional',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_profesional': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueos_agenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloqueoagenda',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueos_agenda', to='clinicas.sede'),
        ),
    ]
