# Generated by Django 5.0.4 on 2026-06-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_h34_bloqueo_agenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='firma_asistencia_documento_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cita',
            name='firma_asistencia_estado',
            field=models.CharField(choices=[('sin_firma', 'Sin firma'), ('enviada', 'Enviada'), ('firmada', 'Firmada'), ('rechazada', 'Rechazada')], default='sin_firma', max_length=20),
        ),
    ]
