# Generated by Django 5.0.4 on 2026-06-16 20:48

import apps.agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_h36_cita_firma_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='firma_asistencia_archivo',
            field=models.FileField(blank=True, null=True, upload_to=apps.agenda.models.cita_firma_asistencia_upload_path),
        ),
    ]
