# Generated by Django 5.0.4 on 2026-05-11 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.users.permissions_catalog import PERMISSION_CATALOG, ROLE_PERMISSION_DEFAULTS


ROLE_LABELS = {
    "admin": ("Administrador", "Rol administrador de la clinica."),
    "recepcion": ("Recepcion", "Rol operativo de recepcion."),
    "profesional": ("Profesional", "Rol de profesional asistencial."),
}


def seed_dynamic_roles(apps, schema_editor):
    Clinica = apps.get_model("clinicas", "Clinica")
    Permiso = apps.get_model("users", "Permiso")
    Rol = apps.get_model("users", "Rol")
    RolPermiso = apps.get_model("users", "RolPermiso")
    User = apps.get_model("users", "User")

    permisos_por_clave = {}
    for clave, modulo, accion, descripcion, assignable in PERMISSION_CATALOG:
        permiso, _ = Permiso.objects.update_or_create(
            clave=clave,
            defaults={
                "modulo": modulo,
                "accion": accion,
                "descripcion": descripcion,
                "assignable": assignable,
                "activo": True,
            },
        )
        permisos_por_clave[clave] = permiso

    for clinica in Clinica.objects.all():
        roles_por_slug = {}
        for slug, (nombre, descripcion) in ROLE_LABELS.items():
            rol, _ = Rol.objects.update_or_create(
                clinica=clinica,
                slug=slug,
                defaults={
                    "nombre": nombre,
                    "descripcion": descripcion,
                    "es_sistema": True,
                    "editable": slug != "admin",
                    "activo": True,
                },
            )
            roles_por_slug[slug] = rol
            keys = ROLE_PERMISSION_DEFAULTS.get(slug, set())
            RolPermiso.objects.bulk_create(
                [
                    RolPermiso(rol=rol, permiso=permisos_por_clave[key])
                    for key in keys
                    if key in permisos_por_clave
                    and not RolPermiso.objects.filter(
                        rol=rol,
                        permiso=permisos_por_clave[key],
                    ).exists()
                ],
                ignore_conflicts=True,
            )

        for user in User.objects.filter(clinica=clinica, rol__in=roles_por_slug.keys(), rol_dinamico__isnull=True):
            user.rol_dinamico = roles_por_slug[user.rol]
            user.save(update_fields=["rol_dinamico"])


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_clinica_telefono'),
        ('users', '0005_passwordresettoken_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(max_length=120, unique=True)),
                ('modulo', models.CharField(max_length=60)),
                ('accion', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('assignable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permisos',
                'ordering': ['modulo', 'accion', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rol_dinamico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='users.rol'),
        ),
        migrations.CreateModel(
            name='RolAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('asignar_permisos', 'Asignar permisos')], max_length=40)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('despues', models.JSONField(blank=True, null=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='users.rol')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roles_auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='users.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='users.rol')),
            ],
            options={
                'db_table': 'roles_permisos',
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', through='users.RolPermiso', to='users.permiso'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='unique_permiso_por_rol'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('clinica', 'slug'), name='unique_rol_slug_por_clinica'),
        ),
        migrations.RunPython(seed_dynamic_roles, migrations.RunPython.noop),
    ]
