# Generated by Django 5.0.4 on 2026-05-11 19:37

from django.db import migrations, models


def mark_professional_roles(apps, schema_editor):
    Rol = apps.get_model("users", "Rol")
    Rol.objects.filter(slug="profesional").update(es_profesional=True)


def unmark_professional_roles(apps, schema_editor):
    Rol = apps.get_model("users", "Rol")
    Rol.objects.filter(slug="profesional").update(es_profesional=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dynamic_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='es_profesional',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_professional_roles, unmark_professional_roles),
    ]
