# Generated by Django 5.0.4 on 2026-06-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sync_cartera_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_profesionales/'),
        ),
        migrations.AddField(
            model_name='user',
            name='registro_profesional',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
