# Generated by Django 5.0.4 on 2026-08-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_firma_digital_registro_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sesion_actual_dispositivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='sesion_actual_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='sesion_actual_iniciada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
