# Generated by Django 5.0.4 on 2026-09-24 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_fotos_subir_ligado_al_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaFirmaToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('ip_captura', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_captura', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas_firma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'captura_firma_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
