# Generated by Django 5.0.4 on 2026-04-15 16:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('clinicas', '0002_servicio_sede'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRecibido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta débito'), ('tarjeta_credito', 'Tarjeta crédito'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagos_recibidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado_parcial', 'Pagado parcial'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobro', to='agenda.cita')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros_como_profesional', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='clinicas.sede')),
            ],
            options={
                'db_table': 'cobros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemCobro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio'), ('insumo_consumo', 'Insumo consumo'), ('producto_retail', 'Producto retail')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cobros.cobro')),
            ],
            options={
                'db_table': 'items_cobro',
            },
        ),
    ]
