# Generated by Django 5.0.4 on 2026-04-15 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_servicio_sede'),
        ('cobros', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcobro',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='itemcobro',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinicas.servicio'),
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cobros.cobro'),
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
