# Generated by Django 5.0.4 on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


def set_origen_cita(apps, schema_editor):
    Cobro = apps.get_model("cobros", "Cobro")
    Cobro.objects.filter(origen__isnull=True).update(origen="cita")
    Cobro.objects.filter(origen="").update(origen="cita")


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0002_itemcotizacion_periodicidad"),
        ("cobros", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cobro",
            name="cotizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cobros",
                to="cotizaciones.cotizacion",
            ),
        ),
        migrations.AddField(
            model_name="cobro",
            name="origen",
            field=models.CharField(
                choices=[("cita", "Por cita"), ("cotizacion", "Por cotizacion / plan"), ("libre", "Ingreso libre")],
                default="cita",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_origen_cita, migrations.RunPython.noop),
    ]
