# Generated by Django 5.0.4 on 2026-09-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_h23_ingresos_unificados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='es_migracion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cobro',
            name='lote_migracion',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='es_migracion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='lote_migracion',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
