PERMISSION_CATALOG = [
    ("agenda.bloqueos.gestionar", "agenda", "bloqueos.gestionar", "Gestionar bloqueos de agenda", False),
    ("agenda.bloqueos.ver", "agenda", "bloqueos.ver", "Ver bloqueos de agenda", True),
    ("agenda.citas.cambiar_estado", "agenda", "citas.cambiar_estado", "Cambiar estado de citas", True),
    ("agenda.citas.confirmar_manual", "agenda", "citas.confirmar_manual", "Confirmar citas manualmente", False),
    ("agenda.citas.crear", "agenda", "citas.crear", "Crear citas", True),
    ("agenda.citas.editar", "agenda", "citas.editar", "Editar citas", True),
    ("agenda.citas.eliminar", "agenda", "citas.eliminar", "Eliminar citas", False),
    ("agenda.citas.ver", "agenda", "citas.ver", "Ver agenda y citas", True),
    ("caja.categorias.gestionar", "caja", "categorias.gestionar", "Gestionar categorias de gasto", False),
    ("caja.categorias.ver", "caja", "categorias.ver", "Ver categorias de gasto", True),
    ("caja.cierre.realizar", "caja", "cierre.realizar", "Realizar cierres de caja", False),
    ("caja.cierre.ver", "caja", "cierre.ver", "Ver cierres de caja", True),
    ("caja.gastos.aprobar", "caja", "gastos.aprobar", "Aprobar o rechazar gastos", False),
    ("caja.gastos.editar", "caja", "gastos.editar", "Editar gastos de caja", False),
    ("caja.gastos.registrar", "caja", "gastos.registrar", "Registrar gastos de caja", True),
    ("caja.gastos.ver", "caja", "gastos.ver", "Ver gastos de caja", True),
    ("clinicas.editar", "clinicas", "editar", "Editar datos de la clinica", False),
    ("clinicas.ver", "clinicas", "ver", "Ver datos de la clinica", True),
    ("cobros.anular", "cobros", "anular", "Anular cobros", False),
    ("cobros.crear", "cobros", "crear", "Crear cobros", True),
    ("cobros.editar_items", "cobros", "editar_items", "Editar items de cobros", True),
    ("cobros.registrar_pago", "cobros", "registrar_pago", "Registrar pagos", True),
    ("cobros.ver", "cobros", "ver", "Ver cobros", True),
    ("cartera.registrar_pago", "cartera", "registrar_pago", "Registrar pagos en cartera", True),
    ("cartera.ver", "cartera", "ver", "Ver cartera", True),
    ("cotizaciones.gestionar", "cotizaciones", "gestionar", "Gestionar cotizaciones", True),
    ("cotizaciones.ver", "cotizaciones", "ver", "Ver cotizaciones", True),
    ("colaboradores.gestionar", "colaboradores", "gestionar", "Gestionar colaboradores", False),
    ("colaboradores.horarios.gestionar", "colaboradores", "horarios.gestionar", "Gestionar horarios", False),
    ("colaboradores.horarios.ver", "colaboradores", "horarios.ver", "Ver horarios", True),
    ("colaboradores.ver", "colaboradores", "ver", "Ver colaboradores", True),
    ("consentimientos.generar", "consentimientos", "generar", "Generar consentimientos", True),
    ("consentimientos.plantillas.gestionar", "consentimientos", "plantillas.gestionar", "Gestionar plantillas", False),
    ("consentimientos.plantillas.ver", "consentimientos", "plantillas.ver", "Ver plantillas", True),
    ("consentimientos.revocar", "consentimientos", "revocar", "Revocar consentimientos", False),
    ("consentimientos.ver", "consentimientos", "ver", "Ver consentimientos", True),
    ("historia.consentimientos.gestionar", "historia", "consentimientos.gestionar", "Gestionar consentimientos informados", True),
    ("historia.fotos.eliminar", "historia", "fotos.eliminar", "Eliminar fotos clinicas", False),
    ("historia.fotos.subir", "historia", "fotos.subir", "Subir fotos clinicas", True),
    ("historia.notas.crear", "historia", "notas.crear", "Crear notas clinicas", True),
    ("historia.ver", "historia", "ver", "Ver historia clinica", True),
    ("inventario.ajustar_stock", "inventario", "ajustar_stock", "Ajustar stock", False),
    ("inventario.categorias.gestionar", "inventario", "categorias.gestionar", "Gestionar categorias de insumos", False),
    ("inventario.insumos.gestionar", "inventario", "insumos.gestionar", "Gestionar insumos", False),
    ("inventario.kardex.ver", "inventario", "kardex.ver", "Ver kardex", True),
    ("inventario.ver", "inventario", "ver", "Ver inventario", True),
    ("notificaciones.email.enviar", "notificaciones", "email.enviar", "Enviar emails administrativos", True),
    ("notificaciones.email.ver_config", "notificaciones", "email.ver_config", "Ver configuracion de email", True),
    ("pacientes.antecedentes.editar", "pacientes", "antecedentes.editar", "Editar antecedentes", True),
    ("pacientes.antecedentes.ver", "pacientes", "antecedentes.ver", "Ver antecedentes", True),
    ("pacientes.crear", "pacientes", "crear", "Crear pacientes", True),
    ("pacientes.editar", "pacientes", "editar", "Editar pacientes", True),
    ("pacientes.eliminar", "pacientes", "eliminar", "Eliminar pacientes", False),
    ("pacientes.ver", "pacientes", "ver", "Ver pacientes", True),
    ("proveedores.gestionar", "proveedores", "gestionar", "Gestionar proveedores", False),
    ("proveedores.ordenes.gestionar", "proveedores", "ordenes.gestionar", "Gestionar ordenes de compra", False),
    ("proveedores.ordenes.recibir", "proveedores", "ordenes.recibir", "Recibir ordenes de compra", False),
    ("proveedores.ordenes.ver", "proveedores", "ordenes.ver", "Ver ordenes de compra", True),
    ("proveedores.ver", "proveedores", "ver", "Ver proveedores", True),
    ("reportes.ver_financieros", "reportes", "ver_financieros", "Ver reportes financieros", True),
    ("reportes.ver_operativos", "reportes", "ver_operativos", "Ver reportes operativos", True),
    ("roles.asignar_permisos", "roles", "asignar_permisos", "Asignar permisos a roles", False),
    ("roles.crear", "roles", "crear", "Crear roles", False),
    ("roles.editar", "roles", "editar", "Editar roles", False),
    ("roles.eliminar", "roles", "eliminar", "Eliminar roles", False),
    ("roles.ver", "roles", "ver", "Ver roles", False),
    ("sedes.eliminar", "sedes", "eliminar", "Eliminar sedes", False),
    ("sedes.gestionar", "sedes", "gestionar", "Gestionar sedes", False),
    ("sedes.ver", "sedes", "ver", "Ver sedes", True),
    ("servicios.gestionar", "servicios", "gestionar", "Gestionar servicios", False),
    ("servicios.ver", "servicios", "ver", "Ver servicios", True),
    ("usuarios.crear", "usuarios", "crear", "Crear usuarios", False),
    ("usuarios.editar", "usuarios", "editar", "Editar usuarios", False),
    ("usuarios.eliminar", "usuarios", "eliminar", "Eliminar usuarios", False),
    ("usuarios.ver", "usuarios", "ver", "Ver usuarios", False),
]

ALL_PERMISSION_KEYS = {item[0] for item in PERMISSION_CATALOG}

ROLE_PERMISSION_DEFAULTS = {
    "admin": ALL_PERMISSION_KEYS,
    "recepcion": {
        "agenda.citas.cambiar_estado",
        "agenda.citas.crear",
        "agenda.citas.editar",
        "agenda.citas.ver",
        "caja.categorias.ver",
        "caja.gastos.registrar",
        "caja.gastos.ver",
        "clinicas.ver",
        "cobros.crear",
        "cobros.editar_items",
        "cobros.registrar_pago",
        "cobros.ver",
        "cartera.registrar_pago",
        "cartera.ver",
        "cotizaciones.ver",
        "colaboradores.horarios.ver",
        "colaboradores.ver",
        "consentimientos.generar",
        "consentimientos.plantillas.ver",
        "consentimientos.ver",
        "historia.consentimientos.gestionar",
        "historia.ver",
        "inventario.kardex.ver",
        "inventario.ver",
        "notificaciones.email.enviar",
        "notificaciones.email.ver_config",
        "pacientes.crear",
        "pacientes.editar",
        "pacientes.ver",
        "proveedores.ordenes.ver",
        "proveedores.ver",
        "reportes.ver_financieros",
        "reportes.ver_operativos",
        "sedes.ver",
        "servicios.ver",
    },
    "profesional": {
        "agenda.citas.ver",
        "caja.categorias.ver",
        "caja.gastos.registrar",
        "caja.gastos.ver",
        "clinicas.ver",
        "cartera.ver",
        "cotizaciones.gestionar",
        "cotizaciones.ver",
        "colaboradores.horarios.ver",
        "colaboradores.ver",
        "consentimientos.generar",
        "consentimientos.plantillas.ver",
        "consentimientos.ver",
        "historia.consentimientos.gestionar",
        "historia.fotos.subir",
        "historia.notas.crear",
        "historia.ver",
        "inventario.kardex.ver",
        "inventario.ver",
        "pacientes.antecedentes.editar",
        "pacientes.antecedentes.ver",
        "pacientes.crear",
        "pacientes.editar",
        "pacientes.ver",
        "proveedores.ordenes.ver",
        "proveedores.ver",
        "reportes.ver_financieros",
        "reportes.ver_operativos",
        "sedes.ver",
        "servicios.ver",
    },
}
