# Generated by Django 5.0.4 on 2026-06-18 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0018_h33_clinica_config_deuda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('objeto_tipo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('detalle', models.JSONField(default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_acciones', to='clinicas.clinica')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinica', 'created_at'], name='core_logacc_clinica_f8ca10_idx'), models.Index(fields=['clinica', 'accion'], name='core_logacc_clinica_8a7dab_idx'), models.Index(fields=['objeto_tipo', 'objeto_id'], name='core_logacc_objeto__315f32_idx')],
            },
        ),
    ]
