# Generated by Django 5.0.4 on 2026-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_factura_proveedor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='numero_factura_proveedor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regimen_tributario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
