# Generated by Django 5.0.4 on 2026-04-13 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_servicio_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(choices=[('empleado', 'Empleado'), ('contratista', 'Contratista'), ('socio', 'Socio')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('numero_documento', models.CharField(max_length=30)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='colaboradores', to='clinicas.servicio')),
                ('sede_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='clinicas.sede')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'colaboradores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
