# Generated by Django 5.0.4 on 2026-05-11 19:37

import django.db.models.deletion
from django.db import migrations, models


def backfill_admin_collaboradores(apps, schema_editor):
    User = apps.get_model("users", "User")
    Colaborador = apps.get_model("colaboradores", "Colaborador")
    Sede = apps.get_model("clinicas", "Sede")
    through_model = Colaborador.sedes.through

    user_field_names = {field.name for field in User._meta.get_fields()}
    if "clinica" not in user_field_names:
        return

    for user in User.objects.filter(rol="admin", clinica__isnull=False).order_by("created_at"):
        if Colaborador.objects.filter(user_id=user.id).exists():
            continue
        sede = Sede.objects.filter(clinica_id=user.clinica_id).order_by("created_at").first()
        colaborador = Colaborador.objects.create(
            user_id=user.id,
            sede_principal_id=sede.id if sede else None,
            tipo_contrato="empleado",
            fecha_ingreso=user.created_at.date(),
            numero_documento="PENDIENTE",
            activo=True,
        )
        if sede:
            through_model.objects.get_or_create(
                colaborador_id=colaborador.id,
                sede_id=sede.id,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_clinica_telefono'),
        ('colaboradores', '0002_colaborador_sedes_horariocolaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='sede_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='clinicas.sede'),
        ),
        migrations.RunPython(backfill_admin_collaboradores, noop_reverse),
    ]
