# Generated by Django 5.0.4 on 2026-10-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_h46_dynamic_roles_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariocolaborador',
            name='no_atiende',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horariocolaborador',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariocolaborador',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
