# Generated by Django 5.0.4 on 2026-04-13 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_servicio_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('NIT', 'NIT')], max_length=3)),
                ('numero_documento', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('canal_confirmacion', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('llamada', 'Llamada')], default='whatsapp', max_length=20)),
                ('autoriza_datos', models.BooleanField(default=False)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'pacientes',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('clinica', 'tipo_documento', 'numero_documento')},
            },
        ),
    ]
