# Generated by Django 5.0.4 on 2026-05-08 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentePaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos_actuales', models.TextField(blank=True)),
                ('condiciones_medicas', models.TextField(blank=True)),
                ('contraindicaciones', models.TextField(blank=True)),
                ('tipo_piel', models.CharField(blank=True, choices=[('I', 'Tipo I - Muy clara, siempre se quema'), ('II', 'Tipo II - Clara, generalmente se quema'), ('III', 'Tipo III - Intermedia, a veces se quema'), ('IV', 'Tipo IV - Morena clara, raramente se quema'), ('V', 'Tipo V - Morena oscura, muy raramente se quema'), ('VI', 'Tipo VI - Muy oscura, nunca se quema')], max_length=3)),
                ('antecedentes_esteticos', models.TextField(blank=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'antecedentes_paciente',
                'ordering': ['-updated_at'],
            },
        ),
    ]
