# Generated by Django 5.0.4 on 2026-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_antecedentepaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentepaciente',
            name='familiares',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='ginecoobstetricos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='patologicos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='quirurgicos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='toxicologicos_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='toxicologicos_drogas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='toxicologicos_otros',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='toxicologicos_tabaquismo',
            field=models.BooleanField(default=False),
        ),
    ]
