# Generated by Django 5.0.4 on 2026-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_antecedentepaciente_familiares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='eps',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('ninguna', 'Sin escolaridad'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnico', 'Tecnico/Tecnologo'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado')], max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Union libre'), ('separado', 'Separado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_etnico',
            field=models.CharField(blank=True, choices=[('mestizo', 'Mestizo'), ('blanco', 'Blanco'), ('afrocolombiano', 'Afrocolombiano/Afrodescendiente'), ('indigena', 'Indigena'), ('raizal', 'Raizal'), ('rom', 'ROM/Gitano'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_responsable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentesco_responsable',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='regimen',
            field=models.CharField(blank=True, choices=[('contributivo', 'Contributivo'), ('subsidiado', 'Subsidiado'), ('vinculado', 'Vinculado'), ('especial', 'Especial/Excepcion'), ('pensionado', 'Pensionado')], max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_responsable',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_afiliado',
            field=models.CharField(blank=True, choices=[('cotizante', 'Cotizante'), ('beneficiario', 'Beneficiario'), ('independiente', 'Independiente'), ('subsidiado', 'Subsidiado'), ('vinculado', 'Vinculado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
