# Generated by Django 5.0.4 on 2026-06-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_barrio_paciente_ciudad_paciente_eps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentepaciente',
            name='abortos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='ant_traumaticos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='cesareas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='fum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='gestaciones',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='metodo_anticonceptivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='partos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='planificacion_familiar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
