# Generated by Django 5.0.4 on 2026-06-24 20:01

import django.db.models.deletion
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_cita_firma_asistencia_signing_token'),
        ('clinicas', '0020_add_facial_fields'),
        ('pacientes', '0005_antecedente_campos_extendidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name='paciente',
            name='embedding_actualizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='embedding_facial',
            field=pgvector.django.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_control',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/fotos_control/'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('confidence', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('match', models.BooleanField()),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('det_score_live', models.FloatField()),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='agenda.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='pacientes.paciente')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkins_faciales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFacial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('umbral_alta', models.FloatField(default=0.85)),
                ('umbral_media', models.FloatField(default=0.7)),
                ('checkin_automatico', models.BooleanField(default=False)),
                ('min_det_score', models.FloatField(default=0.8)),
                ('min_blur_score', models.FloatField(default=60.0)),
                ('min_brightness', models.FloatField(default=50.0)),
                ('max_brightness', models.FloatField(default=230.0)),
                ('max_yaw', models.FloatField(default=25.0)),
                ('max_pitch', models.FloatField(default=20.0)),
                ('max_roll', models.FloatField(default=25.0)),
                ('min_face_area_pct', models.FloatField(default=10.0)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_facial', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'configuracion_facial',
            },
        ),
    ]
