# Generated by Django 5.0.4 on 2026-06-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_add_facial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='foto_live',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/checkins/'),
        ),
    ]
