# Generated by Django 5.0.4 on 2026-08-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_add_foto_live_to_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfacial',
            name='min_det_score',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='configuracionfacial',
            name='min_face_area_pct',
            field=models.FloatField(default=8.0),
        ),
    ]
