# Generated by Django 5.0.4 on 2026-05-26 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0007_servicio_vigencia_meses'),
        ('pacientes', '0002_antecedentepaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='borrador', max_length=20)),
                ('validez_dias', models.PositiveIntegerField(default=30)),
                ('notas', models.TextField(blank=True, default='')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clinicas.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='clinicas.sede')),
            ],
            options={
                'db_table': 'cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagoCotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cuotas', 'Cuotas'), ('financiamiento', 'Financiamiento')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='cotizaciones.cotizacion')),
            ],
            options={
                'db_table': 'formas_pago_cotizacion',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('num_citas', models.PositiveIntegerField(default=1)),
                ('duracion_estimada', models.CharField(blank=True, max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion')),
            ],
            options={
                'db_table': 'items_cotizacion',
                'ordering': ['created_at'],
            },
        ),
    ]
