# Generated by Django 5.0.4 on 2026-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='periodicidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
