# Generated by Django 5.0.4 on 2026-05-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_estados_cotizacion(apps, schema_editor):
    Cotizacion = apps.get_model("cotizaciones", "Cotizacion")
    Cotizacion.objects.filter(estado="enviada").update(estado="borrador")
    Cotizacion.objects.filter(estado="rechazada").update(estado="vencida")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cotizaciones", "0002_itemcotizacion_periodicidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="CotizacionEnvio",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Correo electronico"),
                            ("pdf", "PDF descargado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("destinatario", models.CharField(blank=True, max_length=200)),
                ("notas", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="cotizaciones.cotizacion",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizaciones_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cotizaciones_envios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(migrate_estados_cotizacion, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[("borrador", "Borrador"), ("aceptada", "Aceptada"), ("vencida", "Vencida")],
                default="borrador",
                max_length=20,
            ),
        ),
    ]
