# Generated by Django 5.0.4 on 2026-05-28 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0008_remove_servicio_documenso_template_nombre_and_more'),
        ('cotizaciones', '0003_h24_envios_y_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizacion', to='clinicas.servicio'),
        ),
    ]
