# Generated by Django 5.0.4 on 2026-05-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0009_tratamientocatalogo_tratamientoprocedimiento'),
        ('cotizaciones', '0004_itemcotizacion_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_cotizacion', to='clinicas.tratamientocatalogo'),
        ),
    ]
