# Generated by Codex on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0011_alter_servicio_precio"),
        ("cotizaciones", "0005_itemcotizacion_tratamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcotizacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("tratamiento", "Tratamiento del catalogo"),
                    ("procedimiento", "Procedimiento individual"),
                    ("libre", "Item libre"),
                ],
                default="libre",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="procedimiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_cotizacion_procedimiento",
                to="clinicas.servicio",
            ),
        ),
    ]
