# Generated by Django 5.0.4 on 2026-06-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_h27_1_item_tipo_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagocotizacion',
            name='tipo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('cuotas', 'Cuotas'), ('financiamiento', 'Financiamiento')], max_length=30),
        ),
    ]
