# Generated by Django 5.0.4 on 2026-06-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_add_tarjeta_choices_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagocotizacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
