# Generated by Django 5.0.4 on 2026-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_add_fecha_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='precio_bloqueado',
            field=models.BooleanField(default=False, help_text='True si el valor_unitario fue fijado desde el catalogo y requiere permiso para cambiarse.'),
        ),
    ]
