# Generated by Django 5.0.4 on 2026-06-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_h31_item_precio_bloqueado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aceptada', 'Aceptada'), ('vencida', 'Vencida'), ('descartada', 'Descartada')], default='borrador', max_length=20),
        ),
    ]
