# Generated by Django 5.0.4 on 2026-06-23 14:27

import django.db.models.deletion
from django.db import migrations, models


def backfill_item_campana(apps, schema_editor):
    ItemCotizacion = apps.get_model("cotizaciones", "ItemCotizacion")
    CampanaItem = apps.get_model("clinicas", "CampanaItem")

    items = ItemCotizacion.objects.filter(
        campana__isnull=True,
        activo=True,
    ).select_related("cotizacion")

    for item in items.iterator():
        if not item.procedimiento_id and not item.tratamiento_id:
            continue

        filters = {
            "activo": True,
            "precio_campana": item.valor_unitario,
            "campana__clinica_id": item.cotizacion.clinica_id,
            "campana__activo": True,
        }
        if item.procedimiento_id:
            filters["procedimiento_id"] = item.procedimiento_id
        else:
            filters["tratamiento_id"] = item.tratamiento_id

        for campana_item in CampanaItem.objects.filter(**filters).select_related("campana"):
            campana = campana_item.campana
            sede_ids = list(campana.sedes.values_list("id", flat=True))
            cot_sede_id = item.cotizacion.sede_id
            if sede_ids and cot_sede_id and cot_sede_id not in sede_ids:
                continue
            ItemCotizacion.objects.filter(pk=item.pk).update(campana_id=campana.id)
            break


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0018_h33_clinica_config_deuda'),
        ('cotizaciones', '0010_h39_estado_descartada'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='campana',
            field=models.ForeignKey(blank=True, help_text='Campaña cuyo precio se aplicó en este ítem (para métricas de ventas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_cotizacion', to='clinicas.campana'),
        ),
        migrations.RunPython(backfill_item_campana, migrations.RunPython.noop),
    ]
