# Generated by Django 5.0.4 on 2026-09-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_cotizacion_es_migracion_cotizacion_lote_migracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='sesiones_previas_consumidas',
            field=models.PositiveIntegerField(default=0, help_text='Sesiones que el paciente ya había hecho antes de usar CliniQ (carga de puesta en marcha sin detalle por sesión). Se descuentan de las sesiones agendables restantes.'),
        ),
    ]
