# Generated by Django 5.0.4 on 2026-09-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0040_quitar_otp_fields'),
        ('cotizaciones', '0013_itemcotizacion_sesiones_previas_consumidas'),
        ('inventario', '0007_insumo_permite_stock_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='agendable',
            field=models.BooleanField(default=False, help_text='Solo obsequios de sesión: True si consume una sesión agendable real.'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='cantidad_insumo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='es_obsequio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_obsequio_cotizacion', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='item_origen',
            field=models.ForeignKey(blank=True, help_text='Ítem tratamiento de la misma cotización del que se clona la sesión obsequiada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsequios', to='cotizaciones.itemcotizacion'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='tipo_sesion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_obsequio', to='clinicas.tiposesion'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de lista del obsequio. Solo informativo: no entra al total.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='tipo',
            field=models.CharField(choices=[('tratamiento', 'Tratamiento del catalogo'), ('procedimiento', 'Procedimiento individual'), ('libre', 'Item libre'), ('insumo', 'Producto / insumo')], default='libre', max_length=20),
        ),
    ]
