# Generated by Django 5.0.4 on 2026-09-20 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_itemcotizacion_obsequios'),
        ('inventario', '0008_obsequio_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='entregado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsequios_entregados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='movimiento_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.movimientoinventario'),
        ),
    ]
