# Generated by Django 5.0.4 on 2026-05-26 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0002_itemcotizacion_periodicidad'),
        ('pacientes', '0003_antecedentepaciente_familiares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartera', to='cotizaciones.cotizacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'carteras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuotaCartera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cuotas', 'Cuotas'), ('financiamiento', 'Financiamiento')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_esperada', models.DateField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('valor_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='cartera.cartera')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_cartera_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cuotas_cartera',
                'ordering': ['fecha_esperada', 'created_at'],
            },
        ),
    ]
