# Generated by Django 5.0.4 on 2026-06-12 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotacartera',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_cartera_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuotacartera',
            name='excepcion_aprobada',
            field=models.BooleanField(default=False, help_text='Si True, se permite agendar citas aunque la cuota esté vencida.'),
        ),
    ]
