# Generated by Django 5.0.4 on 2026-06-12 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_h33_cuota_excepcion_aprobada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCarteraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cartera.cuotacartera')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuota_cartera_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cuota_cartera_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
