# Generated by Django 5.0.4 on 2026-09-06 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_cartera_es_migracion_cartera_lote_migracion'),
        ('consentimientos', '0005_consentimiento_plantilla_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotacartera',
            name='anulada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='AcuerdoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveSmallIntegerField(help_text='Secuencial por cartera.')),
                ('motivo', models.TextField()),
                ('saldo_al_proponer', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plan_propuesto', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente_firma', 'Pendiente de firma'), ('vigente', 'Vigente'), ('anulado', 'Anulado'), ('requiere_revision', 'Requiere revisión')], default='pendiente_firma', max_length=20)),
                ('vigente_desde', models.DateTimeField(blank=True, null=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdos_pago_anulados', to=settings.AUTH_USER_MODEL)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='cartera.cartera')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdos_pago_creados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdo_pago', to='consentimientos.consentimiento')),
            ],
            options={
                'db_table': 'acuerdos_pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cuotacartera',
            name='acuerdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas', to='cartera.acuerdopago'),
        ),
        migrations.AddConstraint(
            model_name='acuerdopago',
            constraint=models.UniqueConstraint(fields=('cartera', 'numero'), name='uniq_acuerdo_numero_por_cartera'),
        ),
        migrations.AddConstraint(
            model_name='acuerdopago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente_firma')), fields=('cartera',), name='uniq_acuerdo_pendiente_por_cartera'),
        ),
    ]
