# Generated by Django 5.0.4 on 2026-09-23 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_alter_cuotacartera_medio_pago_and_more'),
        ('clinicas', '0044_backfill_formas_pago'),
        ('cobros', '0005_alter_pagorecibido_medio_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoCuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cartera.cuotacartera')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_cuota', to='clinicas.formadepago')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_cuota', to='cobros.pagorecibido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_cuota_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'abonos_cuota',
                'ordering': ['fecha', 'created_at'],
            },
        ),
    ]
