# Generated by Django 5.0.4 on 2026-04-13 17:00

import apps.historia_clinica.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('clinicas', '0002_servicio_sede'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas', to='clinicas.clinica')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historia_clinica', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'historias_clinicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('procedimiento', 'Procedimiento'), ('evolucion', 'Evolucion'), ('aclaratoria', 'Aclaratoria')], max_length=20)),
                ('anamnesis', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('plan_manejo', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('firmada_en', models.DateTimeField()),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_clinicas', to='agenda.cita')),
                ('firmada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_firmadas', to=settings.AUTH_USER_MODEL)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='historia_clinica.historiaclinica')),
                ('nota_aclarada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aclaraciones', to='historia_clinica.notaclinica')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_clinicas', to='clinicas.servicio')),
            ],
            options={
                'db_table': 'notas_clinicas',
                'ordering': ['firmada_en'],
            },
        ),
        migrations.CreateModel(
            name='FotoClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('antes', 'Antes'), ('durante', 'Durante'), ('despues', 'Despues')], max_length=20)),
                ('archivo', models.ImageField(upload_to=apps.historia_clinica.models.foto_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='historia_clinica.notaclinica')),
            ],
            options={
                'db_table': 'fotos_clinicas',
                'ordering': ['tipo', 'created_at'],
            },
        ),
    ]
