# Generated by Django 5.0.4 on 2026-05-08 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_clinica_telefono'),
        ('historia_clinica', '0001_initial'),
        ('pacientes', '0002_antecedentepaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoclinica',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='cuidados_post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='productos_usados',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='proxima_cita_sugerida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='reacciones_adversas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='tecnica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='zona_tratada',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('general', 'Consentimiento General'), ('toxina_botulinica', 'Toxina Botulinica'), ('rellenos', 'Rellenos Dermicos'), ('laser', 'Laser y Luz Pulsada'), ('peelings', 'Peelings y Exfoliaciones'), ('mesoterapia', 'Mesoterapia'), ('otros', 'Otros procedimientos')], max_length=30)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='consentimientos/')),
                ('url_firmada', models.CharField(blank=True, editable=False, max_length=2048)),
                ('vigencia_meses', models.PositiveIntegerField(default=12)),
                ('fecha_vencimiento', models.DateField(blank=True, editable=False, null=True)),
                ('notas', models.TextField(blank=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_informados', to='clinicas.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_informados', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'consentimientos_informados',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddConstraint(
            model_name='consentimientoinformado',
            constraint=models.UniqueConstraint(fields=('paciente', 'tipo'), name='uniq_consentimiento_informado_paciente_tipo'),
        ),
    ]
