# Generated by Django 5.0.4 on 2026-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0005_remove_consentimiento_unique_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentimientoinformado',
            options={'ordering': ['documenso_template_nombre', 'tipo']},
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='documenso_signing_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
