# Generated by Django 5.0.4 on 2026-05-26 03:15

import apps.historia_clinica.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cita_estado_en_espera'),
        ('clinicas', '0007_servicio_vigencia_meses'),
        ('historia_clinica', '0006_alter_consentimientoinformado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plan_manejo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido', models.TextField()),
                ('contenido_original', models.TextField(blank=True, default='')),
                ('fue_editada', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_medicas', to='agenda.cita')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='historia_clinica.historiaclinica')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_medicas_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes_medicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMedicaAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='historia_clinica.ordenmedica')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_ordenes_medicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes_medicas_auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaOrden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('permite_edicion_profesional', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_ordenes', to='clinicas.clinica')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plantillas_ordenes',
                'ordering': ['nombre', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ordenmedica',
            name='plantilla_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='historia_clinica.plantillaorden'),
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.historia_clinica.models.resultado_examen_upload_path)),
                ('fecha', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_examenes_creados', to=settings.AUTH_USER_MODEL)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='historia_clinica.historiaclinica')),
            ],
            options={
                'db_table': 'resultados_examenes',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
