# Generated by Django 5.0.4 on 2026-05-26 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cita_estado_en_espera'),
        ('historia_clinica', '0007_historiaclinica_motivo_consulta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notaclinica',
            name='causa_externa',
            field=models.CharField(blank=True, choices=[('enfermedad_general', 'Enfermedad General'), ('accidente_trabajo', 'Accidente de Trabajo'), ('accidente_transito', 'Accidente de Transito'), ('lesion_fisica', 'Lesion Fisica'), ('otro', 'Otro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='consecutivo_consulta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='lugar_atencion',
            field=models.CharField(blank=True, choices=[('institucional', 'Institucional'), ('domicilio', 'Domicilio'), ('via_publica', 'Via Publica'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='modalidad_consulta',
            field=models.CharField(blank=True, choices=[('intramural', 'Intramural'), ('extramural', 'Extramural'), ('telemedicina', 'Telemedicina'), ('domiciliaria', 'Domiciliaria')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='tipo_consulta',
            field=models.CharField(blank=True, choices=[('primera_vez', 'Primera Vez'), ('control', 'Control'), ('urgencia', 'Urgencia'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='via_ingreso',
            field=models.CharField(blank=True, choices=[('espontaneo', 'Espontaneo'), ('remitido', 'Remitido'), ('derivado_consulta', 'Derivado de Consulta Externa'), ('otro', 'Otro')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('tension_sistolica', models.SmallIntegerField(blank=True, null=True)),
                ('tension_diastolica', models.SmallIntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.SmallIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.SmallIntegerField(blank=True, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('campos_adicionales', models.JSONField(blank=True, default=list)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos_vitales', to='agenda.cita')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='historia_clinica.historiaclinica')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos_vitales_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signos_vitales',
                'ordering': ['-created_at'],
            },
        ),
    ]
