# Generated by Django 5.0.4 on 2026-08-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0013_anotacionzona_tipo_aplicacion_parametros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignosVitales',
        ),
    ]
