# Generated by Django 5.0.4 on 2026-09-14 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0014_delete_signosvitales'),
        ('inventario', '0002_replace_tipo_with_booleans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_atencion', to='inventario.insumo')),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumo_atencion', to='inventario.movimientoinventario')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_insumo', to='historia_clinica.notaclinica')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_insumo_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consumos_insumo',
                'ordering': ['-created_at'],
            },
        ),
    ]
