# Generated by Django 5.0.4 on 2026-09-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_cita_es_migracion_cita_lote_migracion'),
        ('historia_clinica', '0015_consumoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita en la que se firmó este consentimiento. Solo se usa cuando el procedimiento exige firmar el consentimiento en cada ejecución (no por vigencia).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_informados', to='agenda.cita'),
        ),
    ]
