# Generated by Django 5.0.4 on 2026-09-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_alter_formapagocotizacion_tipo'),
        ('historia_clinica', '0016_consentimientoinformado_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaclinica',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_clinicas', to='cotizaciones.cotizacion'),
        ),
    ]
