# Generated by Django 5.0.4 on 2026-09-24 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0017_notaclinica_cotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='documenso_recipient_paciente_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='documenso_recipient_profesional_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='fecha_firma_profesional',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='firmado_profesional_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_firmados_profesional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='requiere_firma_profesional',
            field=models.BooleanField(default=False, help_text='Copia de la plantilla al crear el sobre: el documento lo firma también el profesional.'),
        ),
    ]
