# Generated by Django 5.0.4 on 2026-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0018_consentimientoinformado_documenso_recipient_paciente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='requiere_tp_profesional',
            field=models.BooleanField(default=False, help_text='El documento lleva el campo de tarjeta profesional: solo lo firma quien tenga TP.'),
        ),
    ]
