# Generated by Django 5.0.4 on 2026-05-28 03:17

import apps.protocolos.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0006_cita_item_cotizacion'),
        ('clinicas', '0008_remove_servicio_documenso_template_nombre_and_more'),
        ('cotizaciones', '0003_h24_envios_y_estados'),
        ('pacientes', '0004_paciente_barrio_paciente_ciudad_paciente_eps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionProcedimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('inasistencia', 'Inasistencia')], default='pendiente', max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('checkin_metodo', models.CharField(blank=True, choices=[('otp_whatsapp', 'OTP WhatsApp'), ('foto_presencial', 'Foto presencial')], max_length=20, null=True)),
                ('checkin_en', models.DateTimeField(blank=True, null=True)),
                ('checkin_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('foto_presencia', models.ImageField(blank=True, null=True, upload_to=apps.protocolos.models.checkin_upload_path)),
                ('foto_presencia_url', models.CharField(blank=True, max_length=2048)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_protocolo', to='agenda.cita')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_protocolo', to='clinicas.pasoprotocolo')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_ejecutadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesiones_procedimiento',
                'ordering': ['paso__orden', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckinOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('expira_en', models.DateTimeField(default=apps.protocolos.models.checkin_otp_default_expira_en)),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='protocolos.sesionprocedimiento')),
            ],
            options={
                'db_table': 'checkin_otps',
            },
        ),
        migrations.CreateModel(
            name='TratamientoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='activo', max_length=20)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('cotizacion_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamiento', to='cotizaciones.itemcotizacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos', to='pacientes.paciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos', to='clinicas.servicio')),
            ],
            options={
                'db_table': 'tratamientos_paciente',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='protocolos.tratamientopaciente'),
        ),
    ]
