# Generated by Django 5.0.4 on 2026-05-30 17:13

import django.db.models.deletion
from django.db import migrations, models


def backfill_sesion_procedimiento(apps, schema_editor):
    SesionProcedimiento = apps.get_model("protocolos", "SesionProcedimiento")
    for sesion in SesionProcedimiento.objects.select_related("paso__servicio").all():
        procedimiento_id = None
        if getattr(sesion, "paso_id", None) and getattr(sesion.paso, "servicio_id", None):
            procedimiento_id = sesion.paso.servicio_id
        elif getattr(sesion, "tratamiento_id", None) and getattr(sesion.tratamiento, "servicio_id", None):
            procedimiento_id = sesion.tratamiento.servicio_id
        if procedimiento_id and sesion.procedimiento_id != procedimiento_id:
            sesion.procedimiento_id = procedimiento_id
            sesion.save(update_fields=["procedimiento"])


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0009_tratamientocatalogo_tratamientoprocedimiento'),
        ('cotizaciones', '0005_itemcotizacion_tratamiento'),
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_tratamiento', to='clinicas.servicio'),
        ),
        migrations.AddField(
            model_name='tratamientopaciente',
            name='tratamiento_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='clinicas.tratamientocatalogo'),
        ),
        migrations.AlterField(
            model_name='tratamientopaciente',
            name='cotizacion_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_paciente', to='cotizaciones.itemcotizacion'),
        ),
        migrations.AlterField(
            model_name='tratamientopaciente',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos', to='clinicas.servicio'),
        ),
        migrations.RunPython(backfill_sesion_procedimiento, migrations.RunPython.noop),
    ]
