# Generated by Django 5.0.4 on 2026-06-01 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0010_tiposesion_tiposesionprocedimiento'),
        ('pacientes', '0004_paciente_barrio_paciente_ciudad_paciente_eps_and_more'),
        ('protocolos', '0002_sesionprocedimiento_procedimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='forzado_sin_consentimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='motivo_forzado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='numero',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='procedimientos_ejecutados',
            field=models.ManyToManyField(blank=True, related_name='sesiones_completadas', to='clinicas.servicio'),
        ),
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='tipo_sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_ejecutadas', to='clinicas.tiposesion'),
        ),
        migrations.CreateModel(
            name='ConsentimientoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_token', models.CharField(max_length=200)),
                ('template_nombre', models.CharField(max_length=200)),
                ('fecha_firma', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('metodo', models.CharField(choices=[('documenso', 'Firma digital Documenso'), ('presencial_pdf', 'Documento fisico escaneado'), ('presencial_confirmado', 'Confirmacion del profesional')], max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='consentimientos_paciente/')),
                ('documenso_envelope_id', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_protocolos', to='pacientes.paciente')),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_pacientes', to='clinicas.servicio')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'protocolos_consentimiento_paciente',
                'ordering': ['-fecha_firma', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='consentimientos_verificados',
            field=models.ManyToManyField(blank=True, related_name='sesiones', to='protocolos.consentimientopaciente'),
        ),
    ]
