# Generated by Django 5.0.4 on 2026-06-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0010_tiposesion_tiposesionprocedimiento'),
        ('protocolos', '0003_sesionprocedimiento_forzado_sin_consentimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionprocedimiento',
            name='paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_protocolo', to='clinicas.pasoprotocolo'),
        ),
    ]
