# Generated by Django 5.0.4 on 2026-09-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_itemcotizacion_obsequios'),
        ('protocolos', '0004_alter_sesionprocedimiento_paso'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionprocedimiento',
            name='item_obsequio',
            field=models.ForeignKey(blank=True, help_text='Obsequio de la cotización que originó esta sesión extra (vacío en las sesiones normales).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_obsequio', to='cotizaciones.itemcotizacion'),
        ),
    ]
