# Generated by Django 5.0.4 on 2026-09-10 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAyuda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('icono', models.CharField(blank=True, help_text="Nombre de icono lucide, ej. 'calendar-days'.", max_length=40)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoría de ayuda',
                'verbose_name_plural': 'categorías de ayuda',
                'db_table': 'ayuda_categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloAyuda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('resumen', models.CharField(blank=True, help_text='Texto corto para las tarjetas y la búsqueda.', max_length=300)),
                ('contenido', models.TextField(blank=True, help_text='Cuerpo del artículo en Markdown.')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube o Vimeo (no listado). Opcional.')),
                ('keywords', models.CharField(blank=True, help_text='Términos extra para la búsqueda, separados por coma.', max_length=255)),
                ('area', models.CharField(blank=True, choices=[('general', 'General'), ('agenda', 'Agenda'), ('pacientes', 'Pacientes'), ('atenciones', 'Atenciones'), ('cotizaciones', 'Cotizaciones'), ('cartera', 'Cartera y cobros'), ('consentimientos', 'Consentimientos'), ('configuracion', 'Configuración'), ('reportes', 'Reportes')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=12)),
                ('publicado_at', models.DateTimeField(blank=True, null=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('util_si', models.PositiveIntegerField(default=0)),
                ('util_no', models.PositiveIntegerField(default=0)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_ayuda_editados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='ayuda.categoriaayuda')),
            ],
            options={
                'verbose_name': 'artículo de ayuda',
                'verbose_name_plural': 'artículos de ayuda',
                'db_table': 'ayuda_articulos',
                'ordering': ['orden', '-publicado_at', '-created_at'],
                'indexes': [models.Index(fields=['estado', 'categoria'], name='ayuda_artic_estado_bd9dec_idx'), models.Index(fields=['estado', 'destacado'], name='ayuda_artic_estado_e18a72_idx')],
            },
        ),
    ]
