# Generated by Django 5.0.4 on 2026-04-15 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_servicio_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_insumos', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'categorias_insumos',
                'ordering': ['nombre'],
                'unique_together': {('clinica', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('consumo_interno', 'Consumo interno'), ('venta_retail', 'Venta retail')], max_length=20)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('ml', 'ml'), ('gr', 'gr'), ('cm', 'cm'), ('par', 'Par'), ('caja', 'Caja')], max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requiere_lote', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventario.categoriainsumo')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('baja', 'Baja')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_promedio_resultante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_resultante', models.DecimalField(decimal_places=3, max_digits=10)),
                ('origen', models.CharField(choices=[('compra', 'Compra'), ('consumo_cita', 'Consumo en cita'), ('venta_retail', 'Venta retail'), ('ajuste_manual', 'Ajuste manual'), ('baja_vencimiento', 'Baja por vencimiento')], max_length=20)),
                ('referencia_id', models.UUIDField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.insumo')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
