# Generated by Django 5.0.4 on 2026-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='insumo',
            name='es_consumo_interno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='es_venta_retail',
            field=models.BooleanField(default=False),
        ),
    ]
