# Generated by Django 5.0.4 on 2026-09-15 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0036_plan_mostrar_publico'),
        ('inventario', '0003_categoria_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='clinicas.sede'),
        ),
        migrations.CreateModel(
            name='StockInsumoSede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_por_sede', to='inventario.insumo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_insumos', to='clinicas.sede')),
            ],
            options={
                'db_table': 'stock_insumo_sede',
                'ordering': ['insumo__nombre'],
                'unique_together': {('insumo', 'sede')},
            },
        ),
    ]
