# Generated by Django 5.0.4 on 2026-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_insumo_permite_stock_negativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='origen',
            field=models.CharField(choices=[('compra', 'Compra'), ('consumo_cita', 'Consumo en cita'), ('venta_retail', 'Venta retail'), ('obsequio', 'Obsequio en cotización'), ('ajuste_manual', 'Ajuste manual'), ('baja_vencimiento', 'Baja por vencimiento')], max_length=20),
        ),
    ]
