# Generated by Django 5.0.4 on 2026-08-24 13:36

import apps.obesidad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionantropometrica',
            name='abdomen_alto_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='abdomen_bajo_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='abdomen_medio_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='pierna_derecha_alto_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='pierna_derecha_bajo_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='pierna_izquierda_alto_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='pierna_izquierda_bajo_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultadolaboratorio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=apps.obesidad.models.laboratorio_upload_path),
        ),
    ]
