# Generated by Django 5.0.4 on 2026-08-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_cita_firma_asistencia_signing_token'),
        ('obesidad', '0002_medicionantropometrica_abdomen_alto_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionantropometrica',
            name='campos_adicionales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_antropometricas', to='agenda.cita'),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='frecuencia_cardiaca',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='frecuencia_respiratoria',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='saturacion_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='medicionantropometrica',
            name='temperatura_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
