# Generated by Django 5.0.4 on 2026-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesidad', '0004_medicionantropometrica_agua_corporal_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicionantropometrica',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
