# Generated by Django 5.0.4 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0002_servicio_sede"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinica",
            name="slot_interval_min",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
