# Generated by Django 5.0.4 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0003_clinica_slot_interval_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinica",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
