# Generated by Django 5.0.4 on 2026-05-28 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_servicio_consentimientos(apps, schema_editor):
    Servicio = apps.get_model("clinicas", "Servicio")
    ServicioConsentimiento = apps.get_model("clinicas", "ServicioConsentimiento")
    DocumensoConsentimientoTemplate = apps.get_model("configuracion", "DocumensoConsentimientoTemplate")

    templates = {
        (template.clinica_id, template.template_token): template
        for template in DocumensoConsentimientoTemplate.objects.all()
    }

    for servicio in Servicio.objects.exclude(documenso_template_token__isnull=True).exclude(documenso_template_token=""):
        template = templates.get((servicio.clinica_id, servicio.documenso_template_token))
        if template is None:
            continue
        ServicioConsentimiento.objects.get_or_create(
            servicio_id=servicio.id,
            template_id=template.id,
            defaults={"orden": 1},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0007_servicio_vigencia_meses'),
        ('configuracion', '0002_configuracionhistoria_configuracionsignosvitales'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tiene_protocolo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ServicioConsentimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_requeridos_set', to='clinicas.servicio')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_que_lo_requieren', to='configuracion.documensoconsentimientotemplate')),
            ],
            options={
                'db_table': 'servicios_consentimientos',
                'ordering': ['orden', 'created_at'],
                'unique_together': {('servicio', 'template')},
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='consentimientos_requeridos',
            field=models.ManyToManyField(blank=True, related_name='servicios', through='clinicas.ServicioConsentimiento', to='configuracion.documensoconsentimientotemplate'),
        ),
        migrations.RunPython(backfill_servicio_consentimientos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='servicio',
            name='documenso_template_nombre',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='documenso_template_token',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='requiere_consentimiento',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_consentimiento',
        ),
        migrations.CreateModel(
            name='PasoProtocolo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('semana', models.PositiveIntegerField(blank=True, null=True)),
                ('es_control', models.BooleanField(default=False)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_protocolo', to='clinicas.servicio')),
            ],
            options={
                'db_table': 'pasos_protocolo',
                'ordering': ['orden', 'created_at'],
                'unique_together': {('servicio', 'orden')},
            },
        ),
    ]
