# Generated by Django 5.0.4 on 2026-05-30 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0008_remove_servicio_documenso_template_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoCatalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_catalogo', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'clinicas_tratamiento_catalogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoProcedimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_catalogo', to='clinicas.servicio')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinicas.tratamientocatalogo')),
            ],
            options={
                'db_table': 'clinicas_tratamiento_procedimiento',
                'ordering': ['orden', 'created_at'],
                'unique_together': {('tratamiento', 'procedimiento')},
            },
        ),
    ]
