# Generated by Django 5.0.4 on 2026-06-01 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0009_tratamientocatalogo_tratamientoprocedimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('es_compromiso', models.BooleanField(default=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_sesion', to='clinicas.tratamientocatalogo')),
            ],
            options={
                'db_table': 'clinicas_tipo_sesion',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoSesionProcedimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_sesion', to='clinicas.servicio')),
                ('tipo_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='clinicas.tiposesion')),
            ],
            options={
                'db_table': 'clinicas_tipo_sesion_procedimiento',
                'ordering': ['orden', 'created_at'],
                'unique_together': {('tipo_sesion', 'procedimiento')},
            },
        ),
    ]
