# Generated by Django 5.0.4 on 2026-06-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0011_alter_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposesion',
            name='duracion_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
