# Generated by Django 5.0.4 on 2026-06-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0012_add_duracion_min_tipo_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='intervalo_recordatorio_horas',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='clinica',
            name='recordatorios_automaticos',
            field=models.BooleanField(default=True),
        ),
    ]
