# Generated by Django 5.0.4 on 2026-06-10 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0013_add_recordatorio_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('max_usuarios', models.PositiveIntegerField(default=0, help_text='Numero maximo de usuarios activos. 0 significa sin limite.')),
            ],
            options={
                'db_table': 'planes',
                'ordering': ['max_usuarios', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='clinica',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas', to='clinicas.plan'),
        ),
    ]
