# Generated by Django 5.0.4 on 2026-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0014_add_plan_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_sedes',
            field=models.PositiveIntegerField(default=0, help_text='Numero maximo de sedes activas. 0 significa sin limite.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio mensual del plan. Null si es gratuito o no aplica.', max_digits=12, null=True),
        ),
    ]
