# Generated by Django 5.0.4 on 2026-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0015_plan_precio_max_sedes_clinica_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo de catalogo para cotizaciones. Si se configura, bloquea el precio en los items de cotizacion.', max_digits=12, null=True),
        ),
    ]
