# Generated by Django 5.0.4 on 2026-06-12 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0016_h31_servicio_precio_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='clinicas.clinica')),
                ('sedes', models.ManyToManyField(blank=True, help_text='Sedes donde aplica la campaña. Vacío = todas las sedes.', related_name='campanas', to='clinicas.sede')),
            ],
            options={
                'db_table': 'campanas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CampanaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precio_campana', models.DecimalField(decimal_places=2, max_digits=12)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinicas.campana')),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campana_items', to='clinicas.servicio')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campana_items', to='clinicas.tratamientocatalogo')),
            ],
            options={
                'db_table': 'campana_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='campanaitem',
            constraint=models.CheckConstraint(check=models.Q(('procedimiento__isnull', False), ('tratamiento__isnull', False), _connector='OR'), name='campana_item_requires_target'),
        ),
    ]
