# Generated by Django 5.0.4 on 2026-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0017_h32_campana_campana_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='bloquear_agenda_por_deuda',
            field=models.BooleanField(default=False, help_text='Si True, impide crear citas a pacientes con cuotas vencidas.'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='dias_gracia_deuda',
            field=models.PositiveIntegerField(default=0, help_text='Días de gracia después del vencimiento antes de bloquear la agenda.'),
        ),
    ]
