# Generated by Django 5.0.4 on 2026-06-24 20:01

import apps.clinicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0019_h34_token_registro_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='token_registro_publico',
            field=models.CharField(default=apps.clinicas.models.generate_token_registro_publico, editable=False, help_text='Token permanente para el link de autoregistro publico de pacientes.', max_length=64, unique=True),
        ),
    ]
