# Generated by Django 5.0.4 on 2026-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0020_add_facial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='onboarding_completado',
            field=models.BooleanField(default=False, help_text='True cuando el admin completa el wizard de configuración inicial.'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del período de prueba. Null si tiene plan asignado.', null=True),
        ),
    ]
