# Generated by Django 5.0.4 on 2026-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0021_add_trial_expires_at_and_onboarding_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
