# Generated by Django 5.0.4 on 2026-06-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0022_extend_telefono_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=100, unique=True)),
                ('nombre_clinica', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=50)),
                ('nombre_admin', models.CharField(max_length=150)),
                ('apellido_admin', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('usado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registros_pendientes',
            },
        ),
    ]
