# Generated by Django 5.0.4 on 2026-06-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0023_add_registro_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='facial_verificacion_habilitada',
            field=models.BooleanField(default=False, help_text='Habilita el módulo de verificación facial biométrica. Add-on de pago activado por superadmin.'),
        ),
    ]
