# Generated by Django 5.0.4 on 2026-07-09 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0026_modulos_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoZonas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_zonas', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'grupos_zonas',
                'ordering': ['nombre'],
                'unique_together': {('clinica', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='GrupoZonasDiagrama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='clinicas.diagramacorporal')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas', to='clinicas.grupozonas')),
            ],
            options={
                'db_table': 'grupos_zonas_diagramas',
                'ordering': ['orden'],
                'unique_together': {('grupo', 'diagrama')},
            },
        ),
        migrations.CreateModel(
            name='ServicioGrupoZonas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='clinicas.grupozonas')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_zonas', to='clinicas.servicio')),
            ],
            options={
                'db_table': 'servicios_grupos_zonas',
                'ordering': ['orden'],
                'unique_together': {('servicio', 'grupo')},
            },
        ),
    ]
