# Generated by Django 5.0.4 on 2026-07-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0027_grupos_zonas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupozonas',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grupozonas',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='grupozonas',
            name='clinica',
        ),
    ]
