# Generated by Django 5.0.4 on 2026-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0028_grupos_zonas_sin_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descuento_maximo_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento maximo permitido en cotizaciones sobre el precio de lista (precio_base). El precio efectivo del item nunca puede bajar de precio_base * (1 - descuento_maximo_pct/100). 0 = no se permite descuento.', max_digits=5),
        ),
        migrations.AddField(
            model_name='tratamientocatalogo',
            name='descuento_maximo_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento maximo permitido en cotizaciones sobre el precio de lista (precio_estimado). El precio efectivo del item nunca puede bajar de precio_estimado * (1 - descuento_maximo_pct/100). 0 = no se permite descuento.', max_digits=5),
        ),
    ]
