# Generated by Django 5.0.4 on 2026-09-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0029_servicio_descuento_maximo_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='modo_puesta_en_marcha',
            field=models.BooleanField(default=False, help_text='Habilita el asistente de puesta en marcha (cargar pacientes en curso, saldos previos, etc.). Lo activa/desactiva el superadmin mientras la clínica migra sus datos.'),
        ),
    ]
