# Generated by Django 5.0.4 on 2026-09-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0031_servicio_precio_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='bloquear_agenda_por_deuda',
            field=models.BooleanField(default=False, help_text='Si True, impide crear citas e iniciar la atención de pacientes con cuotas de cartera vencidas.'),
        ),
    ]
