# Generated by Django 5.0.4 on 2026-09-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0035_quitar_addons_directos_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='mostrar_publico',
            field=models.BooleanField(default=False, help_text='Si esta activo, el plan aparece en la tabla de precios publica de la landing.'),
        ),
    ]
