# Generated by Django 5.0.4 on 2026-09-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0036_plan_mostrar_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio_sede_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo mensual por cada sede por encima de max_sedes. Null si no aplica (ej. plan a medida).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_usuario_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo mensual por cada usuario por encima de max_usuarios. Null si no aplica (ej. plan a medida).', max_digits=12, null=True),
        ),
    ]
