# Generated by Django 5.0.4 on 2026-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0042_servicio_nombre_unico_por_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='filtrar_profesionales_por_procedimiento',
            field=models.BooleanField(default=False, help_text='Si True, al agendar solo se ofrecen los profesionales asociados al procedimiento elegido (Colaborador.especialidades). Si False, cualquier profesional de la sede puede atender cualquier procedimiento.'),
        ),
    ]
