# Generated by Django 5.0.4 on 2026-09-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0041_clinica_filtrar_profesionales_por_procedimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='preparacion',
            field=models.JSONField(blank=True, default=dict, help_text="Preferencias de la pantalla Preparar mi clínica: {'modelo': 'procedimientos'|'tratamientos'|'ambos', 'omitidos': [claves de pasos opcionales]}. El progreso no se guarda: se calcula desde los datos reales."),
        ),
    ]
