# Generated by Django 5.0.4 on 2026-09-22 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0042_clinica_preparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioconsentimiento',
            name='requiere_firma_cada_vez',
            field=models.BooleanField(default=False, help_text='Si True, el paciente debe firmar este consentimiento en cada cita donde se realice el procedimiento, en vez de reutilizar una firma vigente por meses.'),
        ),
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_base', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta débito'), ('tarjeta_credito', 'Tarjeta crédito'), ('credito', 'Crédito'), ('cuotas', 'Cuotas'), ('financiamiento', 'Financiamiento'), ('otro', 'Otro')], max_length=20)),
                ('es_sistema', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='clinicas.clinica')),
            ],
            options={
                'db_table': 'formas_pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='formadepago',
            constraint=models.UniqueConstraint(fields=('clinica', 'nombre'), name='uniq_forma_pago_nombre_por_clinica'),
        ),
    ]
