# Generated by Django 5.0.4 on 2026-09-25 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0044_backfill_formas_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_numero_propio_override',
            field=models.BooleanField(blank=True, default=None, help_text='Anula el addon de número propio de WhatsApp del plan para esta clínica. Null = hereda del plan. Sin el addon base de WhatsApp no tiene efecto.', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_numeros_incluidos_override',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Anula cuántos números propios de WhatsApp puede conectar esta clínica. Null = hereda del plan.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_por_numero_whatsapp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo mensual de referencia por cada número propio de WhatsApp activo.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='whatsapp_numero_propio_habilitado',
            field=models.BooleanField(default=False, help_text='Addon: la clínica envía los WhatsApp desde su propio número (Coexistence vía Lyvio). Requiere el addon base de WhatsApp.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='whatsapp_numeros_incluidos',
            field=models.PositiveIntegerField(default=1, help_text='Números propios de WhatsApp que la clínica puede conectar con el add-on.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
